USE hgbr;

INSERT INTO Turno(idTurno, NombreTurno) VALUES
('M', 'Matutino'),
('V', 'Vespertino'),
('N', 'Nocturno');


INSERT INTO Sexo(idSexo, NombreSexo) VALUES
('M', 'Masculino'),
('F', 'Femenino');

INSERT INTO Ocupacion(NombreOcupacion) VALUES
('Profesionista en el sector privado'),
('Profesionista en dependencia del gobierno'),
('Trabajador agrícola, ganadero, silvícola y de caza o pesca'),
('Vendedor ambulante'),
('Comerciante'),
('Artesano'),
('Trabajador en fábrica'),
('Servicio doméstico'),
('Miembro de las fuerzas armadas mexicanas'),
('Jubilado - Pensionado'),
('Otro');

INSERT INTO EstadoCivil(NombreEstado) VALUES
('Soltero'),
('Casado'),
('Concubinato'),
('Divorciado'),
('Viudo'),
('Prefiero no responder');


INSERT INTO municipio_aguascalientes(NombreMunicipio) VALUES
('Aguascalientes'),
('Asientos'),
('Calvillo'),
('Cosío'),
('Jesús María'),
('Pabellón de Arteaga'),
('Rincón de Romos'),
('San José de Gracia'),
('Tepezalá'),
('El Llano');


INSERT INTO municipio_baja_california(NombreMunicipio) VALUES
('Ensenada'),
('Mexicali'),
('Tecate'),
('Tijuana'),
('Playas de Rosarito');


INSERT INTO municipio_baja_california_sur(NombreMunicipio) VALUES
('Comondú'),
('La Paz'),
('Loreto'),
('Los Cabos'),
('Mulegé');


INSERT INTO municipio_campeche(NombreMunicipio) VALUES
('Calkiní'),
('Campeche'),
('Candelaria'),
('Carmen'),
('Champotón'),
('Hecelchakán'),
('Hopelchén'),
('Palizada'),
('Tenabo'),
('Escárcega');
 
 INSERT INTO municipio_chiapas(NombreMunicipio) VALUES
('Acacoyagua'),
('Acala'),
('Acapetahua'),
('Altamirano'),
('Amatán'),
('Amatenango de la Frontera'),
('Amatenango del Valle'),
('Angel Albino Corzo'),
('Arriaga'),
('Bejucal de Ocampo'),
('Bella Vista'),
('Berriozábal'),
('Bochil'),
('El Bosque'),
('Cacahoatán'),
('Catazajá'),
('Cintalapa'),
('Coapilla'),
('Comitán de Domínguez'),
('La Concordia'),
('Copainalá'),
('Chalchihuitán'),
('Chamula'),
('Chanal'),
('Chapultenango'),
('Chenalhó'),
('Chiapa de Corzo'),
('Chiapilla'),
('Chicoasén'),
('Chicomuselo'),
('Chilón'),
('Escuintla'),
('Francisco León'),
('Frontera Comalapa'),
('Frontera Hidalgo'),
('La Grandeza'),
('Huehuetán'),
('Huixtán'),
('Huitiupán'),
('Huixtla'),
('La Independencia'),
('Ixhuatán'),
('Ixtacomitán'),
('Ixtapa'),
('Ixtapangajoya'),
('Jiquipilas'),
('Jitotol'),
('Juárez'),
('Larráinzar'),
('La Libertad'),
('Mapastepec'),
('Las Margaritas'),
('Mazapa de Madero'),
('Mazatán'),
('Metapa'),
('Mitontic'),
('Motozintla'),
('Nicolás Ruíz'),
('Ocosingo'),
('Ocotepec'),
('Ocozocoautla de Espinosa'),
('Ostuacán'),
('Osumacinta'),
('Oxchuc'),
('Palenque'),
('Pantelhó'),
('Pantepec'),
('Pichucalco'),
('Pijijiapan'),
('El Porvenir'),
('Villa Comaltitlán'),
('Pueblo Nuevo Solistahuacán'),
('Rayón'),
('Reforma'),
('Las Rosas'),
('Sabanilla'),
('Salto de Agua'),
('San Cristóbal de las Casas'),
('San Fernando'),
('Siltepec'),
('Simojovel'),
('Sitalá'),
('Socoltenango'),
('Solosuchiapa'),
('Soyaló'),
('Suchiapa'),
('Suchiate'),
('Sunuapa'),
('Tapachula'),
('Tapalapa'),
('Tapilula'),
('Tecpatán'),
('Tenejapa'),
('Teopisca'),
('Tila'),
('Tonalá'),
('Totolapa'),
('La Trinitaria'),
('Tumbalá'),
('Tuxtla Gutiérrez'),
('Tuxtla Chico'),
('Tuzantán'),
('Tzimol'),
('Unión Juárez'),
('Venustiano Carranza'),
('Villa Corzo'),
('Villaflores'),
('Yajalón'),
('San Lucas'),
('Zinacantán'),
('San Juan Cancuc'),
('Aldama');

 
 INSERT INTO municipio_chihuahua(NombreMunicipio) VALUES
('Ahumada'),
('Aldama'),
('Allende'),
('Aquiles Serdán'),
('Ascensión'),
('Bachíniva'),
('Balleza'),
('Batopilas'),
('Bocoyna'),
('Buenaventura'),
('Camargo'),
('Carichí'),
('Casas Grandes'),
('Chihuahua'),
('Chínipas'),
('Coronado'),
('Coyame del Sotol'),
('La Cruz'),
('Cuauhtémoc'),
('Cusihuiriachi'),
('Delicias'),
('Dr. Belisario Domínguez'),
('Galeana'),
('Santa Isabel'),
('Gómez Farías'),
('Gran Morelos'),
('Guachochi'),
('Guadalupe'),
('Guadalupe y Calvo'),
('Guazapares'),
('Guerrero'),
('Hidalgo del Parral'),
('Huejotitán'),
('Ignacio Zaragoza'),
('Janos'),
('Jiménez'),
('Juárez'),
('Julimes'),
('López'),
('Madera'),
('Maguarichi'),
('Manuel Benavides'),
('Matachí'),
('Matamoros'),
('Meoqui'),
('Morelos'),
('Moris'),
('Namiquipa'),
('Nonoava'),
('Nuevo Casas Grandes'),
('Ocampo'),
('Ojinaga'),
('Praxedis G. Guerrero'),
('Riva Palacio'),
('Rosales'),
('Rosario'),
('San Francisco de Borja'),
('San Francisco de Conchos'),
('San Francisco del Oro'),
('Santa Bárbara'),
('Satevó'),
('Saucillo'),
('Temósachic'),
('El Tule'),
('Urique'),
('Uruachi'),
('Valle de Zaragoza');


INSERT INTO municipio_ciudad_mexico(NombreMunicipio) VALUES
('Álvaro Obregón'),
('Azcapotzalco'),
('Benito Juárez'),
('Coyoacán'),
('Cuajimalpa de Morelos'),
('Cuauhtémoc'),
('Gustavo A. Madero'),
('Iztacalco'),
('Iztapalapa'),
('La Magdalena Contreras'),
('Miguel Hidalgo'),
('Milpa Alta'),
('Tláhuac'),
('Tlalpan'),
('Venustiano Carranza'),
('Xochimilco');


INSERT INTO municipio_coahuila(NombreMunicipio) VALUES
('Abasolo'),
('Acuña'),
('Allende'),
('Arteaga'),
('Candela'),
('Castaños'),
('Cuatro Ciénegas'),
('Escobedo'),
('Francisco I. Madero'),
('Frontera'),
('General Cepeda'),
('Guerrero'),
('Hidalgo'),
('Jiménez'),
('Juárez'),
('Lamadrid'),
('Matamoros'),
('Monclova'),
('Morelos'),
('Múzquiz'),
('Nadadores'),
('Nava'),
('Ocampo'),
('Parras'),
('Piedras Negras'),
('Progreso'),
('Ramos Arizpe'),
('Sabinas'),
('Sacramento'),
('Saltillo'),
('San Buenaventura'),
('San Juan de Sabinas'),
('San Pedro'),
('Sierra Mojada'),
('Torreón'),
('Viesca'),
('Villa Unión'),
('Zaragoza');


INSERT INTO municipio_colima(NombreMunicipio) VALUES
('Armería'),
('Colima'),
('Comala'),
('Coquimatlán'),
('Cuauhtémoc'),
('Ixtlahuacán'),
('Manzanillo'),
('Minatitlán'),
('Tecomán'),
('Villa de Álvarez');


INSERT INTO municipio_durango(NombreMunicipio) VALUES
('Canatlán'),
('Canelas'),
('Coneto de Comonfort'),
('Cuencamé'),
('Durango'),
('General Simón Bolívar'),
('Gómez Palacio'),
('Guadalupe Victoria'),
('Guanaceví'),
('Hidalgo'),
('Indé'),
('Lerdo'),
('Mapimí'),
('Mezquital'),
('Nazas'),
('Nombre de Dios'),
('Ocampo'),
('El Oro'),
('Otáez'),
('Pánuco de Coronado'),
('Peñón Blanco'),
('Poanas'),
('Pueblo Nuevo'),
('Rodeo'),
('San Bernardo'),
('San Dimas'),
('San Juan de Guadalupe'),
('San Juan del Río'),
('San Luis del Cordero'),
('San Pedro del Gallo'),
('Santa Clara'),
('Santiago Papasquiaro'),
('Súchil'),
('Tamazula'),
('Tepehuanes'),
('Tlahualilo'),
('Topia'),
('Vicente Guerrero'),
('Nuevo Ideal');




INSERT INTO municipio_guanajuato(NombreMunicipio) VALUES
('Abasolo'),
('Acámbaro'),
('San Miguel de Allende'),
('Apaseo el Alto'),
('Apaseo el Grande'),
('Atarjea'),
('Celaya'),
('Manuel Doblado'),
('Comonfort'),
('Coroneo'),
('Cortazar'),
('Cuerámaro'),
('Doctor Mora'),
('Dolores Hidalgo Cuna de la Independencia Nacional'),
('Guanajuato'),
('Huanímaro'),
('Irapuato'),
('Jaral del Progreso'),
('Jerécuaro'),
('León'),
('Moroleón'),
('Ocampo'),
('Pénjamo'),
('Pueblo Nuevo'),
('Purísima del Rincón'),
('Romita'),
('Salamanca'),
('Salvatierra'),
('San Diego de la Unión'),
('San Felipe'),
('San Francisco del Rincón'),
('San José Iturbide'),
('San Luis de la Paz'),
('Santa Catarina'),
('Santa Cruz de Juventino Rosas'),
('Santiago Maravatío'),
('Silao de la Victoria'),
('Tarandacuao'),
('Tarimoro'),
('Tierra Blanca'),
('Uriangato'),
('Valle de Santiago'),
('Victoria'),
('Villagrán'),
('Xichú'),
('Yuriria');


INSERT INTO municipio_guerrero(NombreMunicipio) VALUES
('Acapulco de Juárez'),
('Ahuacuotzingo'),
('Ajuchitlán del Progreso'),
('Alcozauca de Guerrero'),
('Alpoyeca'),
('Apaxtla'),
('Arcelia'),
('Atenango del Río'),
('Atlamajalcingo del Monte'),
('Atlixtac'),
('Atoyac de Álvarez'),
('Ayutla de los Libres'),
('Azoyú'),
('Benito Juárez'),
('Buenavista de Cuéllar'),
('Coahuayutla de José María Izazaga'),
('Cocula'),
('Copala'),
('Copalillo'),
('Copanatoyac'),
('Coyuca de Benítez'),
('Coyuca de Catalán'),
('Cuajinicuilapa'),
('Cualác'),
('Cuautepec'),
('Cuetzala del Progreso'),
('Cutzamala de Pinzón'),
('Chilapa de Álvarez'),
('Chilpancingo de los Bravo'),
('Florencio Villarreal'),
('General Canuto A. Neri'),
('General Heliodoro Castillo'),
('Huamuxtitlán'),
('Huitzuco de los Figueroa'),
('Iguala de la Independencia'),
('Igualapa'),
('Ixcateopan de Cuauhtémoc'),
('Zihuatanejo de Azueta'),
('Juan R. Escudero'),
('Leonardo Bravo'),
('Malinaltepec'),
('Mártir de Cuilapan'),
('Metlatónoc'),
('Mochitlán'),
('Olinalá'),
('Ometepec'),
('Pedro Ascencio Alquisiras'),
('Petatlán'),
('Pilcaya'),
('Pungarabato'),
('Quechultenango'),
('San Luis Acatlán'),
('San Marcos'),
('San Miguel Totolapan'),
('Taxco de Alarcón'),
('Tecoanapa'),
('Técpan de Galeana'),
('Teloloapan'),
('Tepecoacuilco de Trujano'),
('Tetipac'),
('Tixtla de Guerrero'),
('Tlacoachistlahuaca'),
('Tlacoapa'),
('Tlalchapa'),
('Tlalixtaquilla de Maldonado'),
('Tlapa de Comonfort'),
('Tlapehuala'),
('La Unión de Isidoro Montes de Oca'),
('Xalpatláhuac'),
('Xochihuehuetlán'),
('Xochistlahuaca'),
('Zapotitlán Tablas'),
('Zirándaro'),
('Zitlala');


INSERT INTO municipio_hidalgo(NombreMunicipio) VALUES
('Acatlán'),
('Acaxochitlán'),
('Actopan'),
('Agua Blanca de Iturbide'),
('Ajacuba'),
('Alfajayucan'),
('Almoloya'),
('Apan'),
('El Arenal'),
('Atitalaquia'),
('Atlapexco'),
('Atotonilco de Tula'),
('Atotonilco el Grande'),
('Calnali'),
('Cardonal'),
('Cuautepec de Hinojosa'),
('Chapantongo'),
('Chapulhuacán'),
('Chilcuautla'),
('Eloxochitlán'),
('Emiliano Zapata'),
('Epazoyucan'),
('Francisco I. Madero'),
('Huasca de Ocampo'),
('Huautla'),
('Huazalingo'),
('Huehuetla'),
('Huejutla de Reyes'),
('Huichapan'),
('Ixmiquilpan'),
('Jacala de Ledezma'),
('Jaltocán'),
('Juárez Hidalgo'),
('Lolotla'),
('Metepec'),
('San Agustín Metzquititlán'),
('Metztitlán'),
('Mineral del Chico'),
('Mineral del Monte'),
('La Misión'),
('Mixquiahuala de Juárez'),
('Molango de Escamilla'),
('Nicolás Flores'),
('Nopala de Villagrán'),
('Omitlán de Juárez'),
('San Felipe Orizatlán'),
('Pacula'),
('Pachuca de Soto'),
('Pisaflores'),
('Progreso de Obregón'),
('Mineral de la Reforma'),
('San Agustín Tlaxiaca'),
('San Bartolo Tutotepec'),
('San Salvador'),
('Santiago de Anaya'),
('Santiago Tulantepec de Lugo Guerrero'),
('Singuilucan'),
('Tasquillo'),
('Tecozautla'),
('Tenango de Doria'),
('Tepeapulco'),
('Tepehuacán de Guerrero'),
('Tepeji del Río de Ocampo'),
('Tepetitlán'),
('Tetepango'),
('Villa de Tezontepec'),
('Tezontepec de Aldama'),
('Tianguistengo'),
('Tizayuca'),
('Tlahuelilpan'),
('Tlahuiltepa'),
('Tlanalapa'),
('Tlanchinol'),
('Tlaxcoapan'),
('Tolcayuca'),
('Tula de Allende'),
('Tulancingo de Bravo'),
('Xochiatipan'),
('Xochicoatlán'),
('Yahualica'),
('Zacualtipán de Ángeles'),
('Zapotlán de Juárez'),
('Zempoala'),
('Zimapán');

-- FALTA JALISCO

INSERT INTO municipio_michoacan(NombreMunicipio) VALUES
('Acuitzio'),
('Aguililla'),
('Álvaro Obregón'),
('Angamacutiro'),
('Angangueo'),
('Apatzingán'),
('Aporo'),
('Aquila'),
('Ario'),
('Arteaga'),
('Briseñas'),
('Buenavista'),
('Carácuaro'),
('Coahuayana'),
('Coalcomán de Vázquez Pallares'),
('Coeneo'),
('Contepec'),
('Copándaro'),
('Cotija'),
('Cuitzeo'),
('Charapan'),
('Charo'),
('Chavinda'),
('Cherán'),
('Chilchota'),
('Chinicuila'),
('Chucándiro'),
('Churintzio'),
('Churumuco'),
('Ecuandureo'),
('Epitacio Huerta'),
('Erongarícuaro'),
('Gabriel Zamora'),
('Hidalgo'),
('La Huacana'),
('Huandacareo'),
('Huaniqueo'),
('Huetamo'),
('Huiramba'),
('Indaparapeo'),
('Irimbo'),
('Ixtlán'),
('Jacona'),
('Jiménez'),
('Jiquilpan'),
('Juárez'),
('Jungapeo'),
('Lagunillas'),
('Madero'),
('Maravatío'),
('Marcos Castellanos'),
('Lázaro Cárdenas'),
('Morelia'),
('Morelos'),
('Múgica'),
('Nahuatzen'),
('Nocupétaro'),
('Nuevo Parangaricutiro'),
('Nuevo Urecho'),
('Numarán'),
('Ocampo'),
('Pajacuarán'),
('Panindícuaro'),
('Parácuaro'),
('Paracho'),
('Pátzcuaro'),
('Penjamillo'),
('Peribán'),
('La Piedad'),
('Purépero'),
('Puruándiro'),
('Queréndaro'),
('Quiroga'),
('Cojumatlán de Régules'),
('Los Reyes'),
('Sahuayo'),
('San Lucas'),
('Santa Ana Maya'),
('Salvador Escalante'),
('Senguio'),
('Susupuato'),
('Tacámbaro'),
('Tancítaro'),
('Tangamandapio'),
('Tangancícuaro'),
('Tanhuato'),
('Taretan'),
('Tarímbaro'),
('Tepalcatepec'),
('Tingambato'),
('Tingüindín'),
('Tiquicheo de Nicolás Romero'),
('Tlalpujahua'),
('Tlazazalca'),
('Tocumbo'),
('Tumbiscatío'),
('Turicato'),
('Tuxpan'),
('Tuzantla'),
('Tzintzuntzan'),
('Tzitzio'),
('Uruapan'),
('Venustiano Carranza'),
('Villamar'),
('Vista Hermosa'),
('Yurécuaro'),
('Zacapu'),
('Zamora'),
('Zináparo'),
('Zinapécuaro'),
('Ziracuaretiro'),
('Zitácuaro');


INSERT INTO municipio_morelos(NombreMunicipio) VALUES
('Amacuzac'),
('Atlatlahucan'),
('Axochiapan'),
('Ayala'),
('Coatlán del Río'),
('Cuautla'),
('Cuernavaca'),
('Emiliano Zapata'),
('Huitzilac'),
('Jantetelco'),
('Jiutepec'),
('Jojutla'),
('Jonacatepec'),
('Mazatepec'),
('Miacatlán'),
('Ocuituco'),
('Puente de Ixtla'),
('Temixco'),
('Temoac'),
('Tepalcingo'),
('Tepoztlán'),
('Tetecala'),
('Tetela del Volcán'),
('Tlalnepantla'),
('Tlaltizapán de Zapata'),
('Tlaquiltenango'),
('Tlayacapan'),
('Totolapan'),
('Xochitepec'),
('Yautepec'),
('Yecapixtla'),
('Zacatepec'),
('Zacualpan de Amilpas');


INSERT INTO municipio_nayarit(NombreMunicipio) VALUES
('Acaponeta'),
('Ahuacatlán'),
('Amatlán de Cañas'),
('Compostela'),
('Huajicori'),
('Ixtlán del Río'),
('Jala'),
('Xalisco'),
('Del Nayar'),
('Rosamorada'),
('Ruíz'),
('San Blas'),
('San Pedro Lagunillas'),
('Santa María del Oro'),
('Santiago Ixcuintla'),
('Tecuala'),
('Tepic'),
('Tuxpan'),
('La Yesca'),
('Bahía de Banderas');


INSERT INTO municipio_nuevo_leon(NombreMunicipio) VALUES
('Abasolo'),
('Agualeguas'),
('Los Aldamas'),
('Allende'),
('Anáhuac'),
('Apodaca'),
('Aramberri'),
('Bustamante'),
('Cadereyta Jiménez'),
('El Carmen'),
('Cerralvo'),
('Ciénega de Flores'),
('China'),
('Doctor Arroyo'),
('Doctor Coss'),
('Doctor González'),
('Galeana'),
('García'),
('San Pedro Garza García'),
('General Bravo'),
('General Escobedo'),
('General Terán'),
('General Treviño'),
('General Zaragoza'),
('General Zuazua'),
('Guadalupe'),
('Los Herreras'),
('Higueras'),
('Hualahuises'),
('Iturbide'),
('Juárez'),
('Lampazos de Naranjo'),
('Linares'),
('Marín'),
('Melchor Ocampo'),
('Mier y Noriega'),
('Mina'),
('Montemorelos'),
('Monterrey'),
('Parás'),
('Pesquería'),
('Los Ramones'),
('Rayones'),
('Sabinas Hidalgo'),
('Salinas Victoria'),
('San Nicolás de los Garza'),
('Hidalgo'),
('Santa Catarina'),
('Santiago'),
('Vallecillo'),
('Villaldama');

-- FALTA OAXACA (SON UN CHINGO)
-- FALTA PUEBLA

INSERT INTO municipio_queretaro(NombreMunicipio) VALUES
('Amealco de Bonfil'),
('Pinal de Amoles'),
('Arroyo Seco'),
('Cadereyta de Montes'),
('Colón'),
('Corregidora'),
('Ezequiel Montes'),
('Huimilpan'),
('Jalpan de Serra'),
('Landa de Matamoros'),
('El Marqués'),
('Pedro Escobedo'),
('Peñamiller'),
('Querétaro'),
('San Joaquín'),
('San Juan del Río'),
('Tequisquiapan'),
('Tolimán');


INSERT INTO municipio_quintana(NombreMunicipio) VALUES
('Cozumel'),
('Felipe Carrillo Puerto'),
('Isla Mujeres'),
('Othón P. Blanco'),
('Benito Juárez'),
('José María Morelos'),
('Lázaro Cárdenas'),
('Solidaridad'),
('Tulum'),
('Bacalar');


INSERT INTO municipio_san_luis(NombreMunicipio) VALUES
('Ahualulco'),
('Alaquines'),
('Aquismón'),
('Armadillo de los Infante'),
('Axtla de Terrazas'),
('Cárdenas'),
('Catorce'),
('Cedral'),
('Cerritos'),
('Cerro de San Pedro'),
('Ciudad del Maíz'),
('Ciudad Fernández'),
('Tancanhuitz'),
('Ciudad Valles'),
('Coxcatlán'),
('Charcas'),
('Ebano'),
('Guadalcázar'),
('Huehuetlán'),
('Lagunillas'),
('Matehuala'),
('Mexquitic de Carmona'),
('Moctezuma'),
('Rayón'),
('Rioverde'),
('Salinas'),
('San Antonio'),
('San Ciro de Acosta'),
('San Luis Potosí'),
('San Martín Chalchicuautla'),
('San Nicolás Tolentino'),
('Santa Catarina'),
('Santa María del Río'),
('Santo Domingo'),
('San Vicente Tancuayalab'),
('Soledad de Graciano Sánchez'),
('Tamasopo'),
('Tamazunchale'),
('Tampacán'),
('Tampamolón Corona'),
('Tamuín'),
('Tanlajás'),
('Tanquián de Escobedo'),
('Tierra Nueva'),
('Vanegas'),
('Venado'),
('Villa de Arriaga'),
('Villa de Guadalupe'),
('Villa de la Paz'),
('Villa de Ramos'),
('Villa de Reyes'),
('Villa Hidalgo'),
('Villa Juárez'),
('Agualeguas'),
('Villa de Arista'),
('Matlapa'),
('Xilitla'),
('Zaragoza');

INSERT INTO municipio_sinaloa(NombreMunicipio) VALUES
('Ahome'),
('Angostura'),
('Badiraguato'),
('Concordia'),
('Cosalá'),
('Culiacán'),
('Choix'),
('Elota'),
('Escuinapa'),
('El Fuerte'),
('Guasave'),
('Mazatlán'),
('Mocorito'),
('Rosario'),
('Salvador Alvarado'),
('San Ignacio'),
('Sinaloa'),
('Navolato');


INSERT INTO municipio_sonora(NombreMunicipio) VALUES
('Aconchi'),
('Agua Prieta'),
('Alamos'),
('Altar'),
('Arivechi'),
('Arizpe'),
('Atil'),
('Bacadéhuachi'),
('Bacanora'),
('Bacerac'),
('Bacoachi'),
('Bácum'),
('Banámichi'),
('Baviácora'),
('Bavispe'),
('Benito Juárez'),
('Benjamín Hill'),
('Caborca'),
('Cajeme'),
('Cananea'),
('Carbó'),
('La Colorada'),
('Cucurpe'),
('Cumpas'),
('Divisaderos'),
('Empalme'),
('Etchojoa'),
('Fronteras'),
('Granados'),
('Guaymas'),
('Hermosillo'),
('Huachinera'),
('Huásabas'),
('Huatabampo'),
('Huépac'),
('Imuris'),
('Magdalena'),
('Mazatán'),
('Moctezuma'),
('Naco'),
('Nácori Chico'),
('Nacozari de García'),
('Navojoa'),
('Nogales'),
('Onavas'),
('Opodepe'),
('Oquitoa'),
('Pitiquito'),
('Puerto Peñasco'),
('Quiriego'),
('Rayón'),
('Rosario'),
('Sahuaripa'),
('San Felipe de Jesús'),
('San Javier'),
('San Luis Río Colorado'),
('San Miguel de Horcasitas'),
('San Pedro de la Cueva'),
('Santa Ana'),
('Santa Cruz'),
('Sáric'),
('Soyopa'),
('Suaqui Grande'),
('Tepache'),
('Trincheras'),
('Tubutama'),
('Ures'),
('Villa Hidalgo'),
('Villa Pesqueira'),
('Yécora'),
('General Plutarco Elías Calles'),
('Benito Juárez'),
('San Ignacio Río Muerto');


INSERT INTO municipio_tabasco(NombreMunicipio) VALUES
('Balancán'),
('Cárdenas'),
('Centla'),
('Centro'),
('Comalcalco'),
('Cunduacán'),
('Emiliano Zapata'),
('Huimanguillo'),
('Jalapa'),
('Jalpa de Méndez'),
('Jonuta'),
('Macuspana'),
('Nacajuca'),
('Paraíso'),
('Tacotalpa'),
('Teapa'),
('Tenosique');


INSERT INTO municipio_tamaulipas(NombreMunicipio) VALUES
('Abasolo'),
('Aldama'),
('Altamira'),
('Antiguo Morelos'),
('Burgos'),
('Bustamante'),
('Camargo'),
('Casas'),
('Ciudad Madero'),
('Cruillas'),
('Gómez Farías'),
('González'),
('Güémez'),
('Guerrero'),
('Gustavo Díaz Ordaz'),
('Hidalgo'),
('Jaumave'),
('Jiménez'),
('Llera'),
('Mainero'),
('El Mante'),
('Matamoros'),
('Méndez'),
('Mier'),
('Miguel Alemán'),
('Miquihuana'),
('Nuevo Laredo'),
('Nuevo Morelos'),
('Ocampo'),
('Padilla'),
('Palmillas'),
('Reynosa'),
('Río Bravo'),
('San Carlos'),
('San Fernando'),
('San Nicolás'),
('Soto la Marina'),
('Tampico'),
('Tula'),
('Valle Hermoso'),
('Victoria'),
('Villagrán'),
('Xicoténcatl');


INSERT INTO municipio_tlaxcala(NombreMunicipio) VALUES
('Amaxac de Guerrero'),
('Apetatitlán de Antonio Carvajal'),
('Atlangatepec'),
('Altzayanca'),
('Apizaco'),
('Calpulalpan'),
('El Carmen Tequexquitla'),
('Cuapiaxtla'),
('Cuaxomulco'),
('Chiautempan'),
('Muñoz de Domingo Arenas'),
('Españita'),
('Huamantla'),
('Hueyotlipan'),
('Ixtacuixtla de Mariano Matamoros'),
('Ixtenco'),
('Mazatecochco de José María Morelos'),
('Contla de Juan Cuamatzi'),
('Tepetitla de Lardizábal'),
('Sanctórum de Lázaro Cárdenas'),
('Nanacamilpa de Mariano Arista'),
('Acuamanala de Miguel Hidalgo'),
('Natívitas'),
('Panotla'),
('San Pablo del Monte'),
('Santa Cruz Tlaxcala'),
('Tenancingo'),
('Teolocholco'),
('Tepeyanco'),
('Terrenate'),
('Tetla de la Solidaridad'),
('Tetlatlahuca'),
('Tlaxcala'),
('Tlaxco'),
('Tocatlán'),
('Totolac'),
('Ziltlaltépec de Trinidad Sánchez Santos'),
('Tzompantepec'),
('Xaloztoc'),
('Xaltocan'),
('Papalotla de Xicohténcatl'),
('Xicohtzinco'),
('Yauhquemehcan'),
('Zacatelco'),
('Benito Juárez'),
('Emiliano Zapata'),
('Lázaro Cárdenas'),
('La Magdalena Tlaltelulco'),
('San Damián Texoloc'),
('San Francisco Tetlanohcan'),
('San Jerónimo Zacualpan'),
('San José Teacalco'),
('San Juan Huactzinco'),
('San Lorenzo Axocomanitla'),
('San Lucas Tecopilco'),
('Santa Ana Nopalucan'),
('Santa Apolonia Teacalco'),
('Santa Catarina Ayometla'),
('Santa Cruz Quilehtla'),
('Santa Isabel Xiloxoxtla');


INSERT INTO municipio_veracruz(NombreMunicipio) VALUES
('Acajete'),
('Acatlán'),
('Acayucan'),
('Actopan'),
('Acula'),
('Acultzingo'),
('Camarón de Tejeda'),
('Alpatláhuac'),
('Alto Lucero de Gutiérrez Barrios'),
('Altotonga'),
('Alvarado'),
('Amatitlán'),
('Naranjos Amatlán'),
('Amatlán de los Reyes'),
('Angel R. Cabada'),
('La Antigua'),
('Apazapan'),
('Aquila'),
('Astacinga'),
('Atlahuilco'),
('Atoyac'),
('Atzacan'),
('Atzalan'),
('Tlaltetela'),
('Ayahualulco'),
('Banderilla'),
('Benito Juárez'),
('Boca del Río'),
('Calcahualco'),
('Camerino Z. Mendoza'),
('Carrillo Puerto'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Citlaltépetl'),
('Coacoatzintla'),
('Coahuitlán'),
('Coatepec'),
('Coatzacoalcos'),
('Coatzintla'),
('Coetzala'),
('Colipa'),
('Comapa'),
('Córdoba'),
('Cosamaloapan de Carpio'),
('Cosautlán de Carvajal'),
('Coscomatepec'),
('Cosoleacaque'),
('Cotaxtla'),
('Coxquihui'),
('Coyutla'),
('Cuichapa'),
('Cuitláhuac'),
('Chacaltianguis'),
('Chalma'),
('Chiconamel'),
('Chiconquiaco'),
('Chicontepec'),
('Chinameca'),
('Chinampa de Gorostiza'),
('Las Choapas'),
('Chocamán'),
('Chontla'),
('Chumatlán'),
('Emiliano Zapata'),
('Espinal'),
('Filomeno Mata'),
('Fortín'),
('Gutiérrez Zamora'),
('Hidalgotitlán'),
('Huatusco'),
('Huayacocotla'),
('Hueyapan de Ocampo'),
('Huiloapan de Cuauhtémoc'),
('Ignacio de la Llave'),
('Ilamatlán'),
('Isla'),
('Ixcatepec'),
('Ixhuacán de los Reyes'),
('Ixhuatlán del Café'),
('Ixhuatlancillo'),
('Ixhuatlán del Sureste'),
('Ixhuatlán de Madero'),
('Ixmatlahuacan'),
('Ixtaczoquitlán'),
('Jalacingo'),
('Xalapa'),
('Jalcomulco'),
('Jáltipan'),
('Jamapa'),
('Jesús Carranza'),
('Xico'),
('Jilotepec'),
('Juan Rodríguez Clara'),
('Juchique de Ferrer'),
('Landero y Coss'),
('Lerdo de Tejada'),
('Magdalena'),
('Maltrata'),
('Manlio Fabio Altamirano'),
('Mariano Escobedo'),
('Martínez de la Torre'),
('Mecatlán'),
('Mecayapan'),
('Medellín de Bravo'),
('Miahuatlán'),
('Las Minas'),
('Minatitlán'),
('Misantla'),
('Mixtla de Altamirano'),
('Moloacán'),
('Naolinco'),
('Naranjal'),
('Nautla'),
('Nogales'),
('Oluta'),
('Omealca'),
('Orizaba'),
('Otatitlán'),
('Oteapan'),
('Ozuluama de Mascareñas'),
('Pajapan'),
('Pánuco'),
('Papantla'),
('Paso del Macho'),
('Paso de Ovejas'),
('La Perla'),
('Perote'),
('Platón Sánchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Las Vigas de Ramírez'),
('Pueblo Viejo'),
('Puente Nacional'),
('Rafael Delgado'),
('Rafael Lucio'),
('Los Reyes'),
('Río Blanco'),
('Saltabarranca'),
('San Andrés Tenejapan'),
('San Andrés Tuxtla'),
('San Juan Evangelista'),
('Santiago Tuxtla'),
('Sayula de Alemán'),
('Soconusco'),
('Sochiapa'),
('Soledad Atzompa'),
('Soledad de Doblado'),
('Soteapan'),
('Tamalín'),
('Tamiahua'),
('Tampico Alto'),
('Tancoco'),
('Tantima'),
('Tantoyuca'),
('Tatatila'),
('Castillo de Teayo'),
('Tecolutla'),
('Tehuipango'),
('Álamo Temapache'),
('Tempoal'),
('Tenampa'),
('Tenochtitlán'),
('Teocelo'),
('Tepatlaxco'),
('Tepetlán'),
('Tepetzintla'),
('Tequila'),
('José Azueta'),
('Texcatepec'),
('Texhuacán'),
('Texistepec'),
('Tezonapa'),
('Tierra Blanca'),
('Tihuatlán'),
('Tlacojalpan'),
('Tlacolulan'),
('Tlacotalpan'),
('Tlacotepec de Mejía'),
('Tlachichilco'),
('Tlalixcoyan'),
('Tlalnelhuayocan'),
('Tlapacoyan'),
('Tlaquilpa'),
('Tlilapan'),
('Tomatlán'),
('Tonayán'),
('Totutla'),
('Tuxpan'),
('Tuxtilla'),
('Ursulo Galván'),
('Vega de Alatorre'),
('Veracruz'),
('Villa Aldama'),
('Xoxocotla'),
('Yanga'),
('Yecuatla'),
('Zacualpan'),
('Zaragoza'),
('Zentla'),
('Zongolica'),
('Zontecomatlán de López y Fuentes'),
('Zozocolco de Hidalgo'),
('Agua Dulce'),
('El Higo'),
('Nanchital de Lázaro Cárdenas del Río'),
('Tres Valles'),
('Carlos A. Carrillo'),
('Tatahuicapan de Juárez'),
('Uxpanapa'),
('San Rafael'),
('Santiago Sochiapan');


INSERT INTO municipio_yucatan(NombreMunicipio) VALUES
('Abalá'),
('Acanceh'),
('Akil'),
('Baca'),
('Bokobá'),
('Buctzotz'),
('Cacalchén'),
('Calotmul'),
('Cansahcab'),
('Cantamayec'),
('Celestún'),
('Cenotillo'),
('Conkal'),
('Cuncunul'),
('Cuzamá'),
('Chacsinkín'),
('Chankom'),
('Chapab'),
('Chemax'),
('Chicxulub Pueblo'),
('Chichimilá'),
('Chikindzonot'),
('Chocholá'),
('Chumayel'),
('Dzán'),
('Dzemul'),
('Dzidzantún'),
('Dzilam de Bravo'),
('Dzilam González'),
('Dzitás'),
('Dzoncauich'),
('Espita'),
('Halachó'),
('Hocabá'),
('Hoctún'),
('Homún'),
('Huhí'),
('Hunucmá'),
('Ixil'),
('Izamal'),
('Kanasín'),
('Kantunil'),
('Kaua'),
('Kinchil'),
('Kopomá'),
('Mama'),
('Maní'),
('Maxcanú'),
('Mayapán'),
('Mérida'),
('Mocochá'),
('Motul'),
('Muna'),
('Muxupip'),
('Opichén'),
('Oxkutzcab'),
('Panabá'),
('Peto'),
('Progreso'),
('Quintana Roo'),
('Río Lagartos'),
('Sacalum'),
('Samahil'),
('Sanahcat'),
('San Felipe'),
('Santa Elena'),
('Seyé'),
('Sinanché'),
('Sotuta'),
('Sucilá'),
('Sudzal'),
('Suma'),
('Tahdziú'),
('Tahmek'),
('Teabo'),
('Tecoh'),
('Tekal de Venegas'),
('Tekantó'),
('Tekax'),
('Tekit'),
('Tekom'),
('Telchac Pueblo'),
('Telchac Puerto'),
('Temax'),
('Temozón'),
('Tepakán'),
('Tetiz'),
('Teya'),
('Ticul'),
('Timucuy'),
('Tinum'),
('Tixcacalcupul'),
('Tixkokob'),
('Tixméhuac'),
('Tixpéhual'),
('Tizimín'),
('Tunkás'),
('Tzucacab'),
('Uayma'),
('Ucú'),
('Umán'),
('Valladolid'),
('Xocchel'),
('Yaxcabá'),
('Yaxkukul'),
('Yobaín');


INSERT INTO municipio_zacatecas(NombreMunicipio) VALUES
('Apozol'),
('Apulco'),
('Atolinga'),
('Benito Juárez'),
('Calera'),
('Cañitas de Felipe Pescador'),
('Concepción del Oro'),
('Cuauhtémoc'),
('Chalchihuites'),
('Fresnillo'),
('Trinidad García de la Cadena'),
('Genaro Codina'),
('General Enrique Estrada'),
('General Francisco R. Murguía'),
('El Plateado de Joaquín Amaro'),
('General Pánfilo Natera'),
('Guadalupe'),
('Huanusco'),
('Jalpa'),
('Jerez'),
('Jiménez del Teul'),
('Juan Aldama'),
('Juchipila'),
('Loreto'),
('Luis Moya'),
('Mazapil'),
('Melchor Ocampo'),
('Mezquital del Oro'),
('Miguel Auza'),
('Momax'),
('Monte Escobedo'),
('Morelos'),
('Moyahua de Estrada'),
('Nochistlán de Mejía'),
('Noria de Ángeles'),
('Ojocaliente'),
('Pánuco'),
('Pinos'),
('Río Grande'),
('Sain Alto'),
('El Salvador'),
('Sombrerete'),
('Susticacán'),
('Tabasco'),
('Tepechitlán'),
('Tepetongo'),
('Teúl de González Ortega'),
('Tlaltenango de Sánchez Román'),
('Valparaíso'),
('Vetagrande'),
('Villa de Cos'),
('Villa García'),
('Villa González Ortega'),
('Villa Hidalgo'),
('Villanueva'),
('Zacatecas');



INSERT INTO Habiencia(NombreHabiencia) VALUES
('INSABI'),
('IMSS'),
('ISSSTE'),
('PEMEX'),
('SM');
