USE hgbr;

INSERT INTO Sexo(nombre) VALUES
('M'),
('F');

INSERT INTO estado_conyugal(nombre) VALUES
('Soltero'),
('Casado'),
('Concubinato'),
('Divorciado'),
('Viudo'),
('Prefiero no responder');

INSERT INTO tipo_vialidad(nombre) VALUES
('Ampliación'),
('Andador'),
('Avenidad'),
('Boulevard'),
('Calle'),
('Callejón'),
('Calzada'),
('Cerrada'),
('Circuito'),
('Circunvalación'),
('Continuación'),
('Corredor'),
('Diagonal'),
('Eje Vial'),
('Pasaje'),
('Peatonal'),
('Periférico'),
('Privada'),
('Prolongación'),
('Retorno'),
('Viaducto'),
('Ninguno'),
('Carretera'),
('Camino'),
('Terracería'),
('Brecha'),
('Vereda');

INSERT INTO tipo_asentamiento(nombre) VALUES
('Aeropuerto'),
('Ampliación'),
('Barrio'),
('Cantón'),
('Ciudad'),
('Ciudad Industrial'),
('Colonia'),
('Condominio'),
('Conjunto Habitacional'),
('Corredor Industrial'),
('Coto'),
('Cuartel'),
('Ejido'),
('Exhacienda'),
('Fracción'),
('Fraccionamiento'),
('Granja'),
('Hacienda'),
('Ingenio'),
('Manzana'),
('Paraje'),
('Parque Industrial'),
('Privada'),
('Prolongación'),
('Pueblo'),
('Puerto'),
('Ranchería'),
('Rancho'),
('Región'),
('Residencial'),
('Rinconada'),
('Sección'),
('Sector'),
('Super Manzana'),
('Unidad'),
('Unidad Habitacional'),
('Villa'),
('Zona Federal'),
('Zona Industrial'),
('Zona Militar'),
('Ninguno'),
('Zona Naval');

INSERT INTO pacientes(folio, nombre, primer_apellido, segundo_apellido, curp, fecha_nacimiento, entidad_nacimiento, edad, nacido_hospital, fk_sexo, peso, talla, fk_estado_conyugal, insabi, gratuitidad, indigena, lengua_indigena, cual_lengua, fk_tipo_vialidad, nombre_vialidad, num_ext, num_int, fk_tipo_asentamiento, nombre_asentamiento, cp, localidad, municipio_deleg, entidad_federativa, pais, telefono) VALUES
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('');